### ISSUE TITLE
What license is this?

### ISSUE THREAD

**Issue by ralphbean** [openshift/python-interface#14]
"Unknown" is in setup.py and there's no license file.

**Comment by FrostyX** [comment]
Now there is a [LICENSE](https://github.com/openshift/python-interface/blob/master/LICENSE) file and in `setup.py` there is

    license = "Aache v2",

although it has a typo.

**Comment by pruan-rht** [comment]
@ralphbean, @FrostyX,  I've updated the typo.  Thanks for the feedback!
